database:
  host: "127.0.0.1"
  port: 3306
  name: "minecraft"
  username: "root"
  password: "password"

modules:
  ExampleModule:
    enabled: true
  GamemodeModule:
    enabled: false
  GodModeModule:
    enabled: false
